# Generated by Django 2.0 on 2017-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessthenumber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='secret_code',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='bulls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='cows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='move',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='secret_number',
            field=models.IntegerField(default=0),
        ),
    ]
