# Generated by Django 2.0 on 2017-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessthenumber', '0002_auto_20171218_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='secret_number',
            field=models.CharField(max_length=10),
        ),
    ]
